# This workflow will install Python dependencies, run tests and lint with a variety of Python versions ss8
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: delete-action

on:
  workflow_dispatch:
    inputs:
      event:
        type: choice
        options:
          - 'delete'
        description: 'only for test'
  schedule:
    - cron: '0 0 10 9 *'  # 매년 9월 10일 00:00 UTC에 실행

jobs:
  delete-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Delete .github action directory
        run: |
          rm -rf .github
      - name: Commits
        run: |
          git config --local user.email "absinthe4902@naver.com"
          git config --local user.name "AUTO_COMMIT_GIT_ACTION"
          git pull
          git add .
          git commit -m "AUTO DELETE: Delete github action on 2024/09/10 UTC"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $